{* HEADER *}

<div class="crm-submit-buttons">
<hr>
</div>

  <h6>Generate report manually, this will generate report using following, however they will not be saved as generated report in the database</h1>
  <hr>
  <br>
  {* choose date this report will not be saved to database as reported *}
  <div>
    <span>{$form.start_date.label}</span>
    <span>{$form.start_date.html}</span>
    <span>{$form.end_date.label}</span>
    <span>{$form.end_date.html}</span>
  </div>
  <br>
  <h6>Regenerate autogenerated reports (Autogenerated report: this will happen when press <b>Generate report</b> button withot selecting any filter)</h1>
  <hr>
  <br>
  {* old reports list, this will happen when you press generate button without selecting filter *}
  <div>
    <span>{$form.old_report.label}</span>
    <span>{$form.old_report.html}</span>
  </div>
  <br>
{* {foreach from=$elementNames item=elementName}
  <div class="crm-section">
    <div class="label">{$form.$elementName.label}</div>
    <div class="content">{$form.$elementName.html}</div>
    <div class="clear"></div>
  </div>
{/foreach} *}

{* FIELD EXAMPLE: OPTION 2 (MANUAL LAYOUT)

  <div>
    <span>{$form.value.label}</span>
    <span>{$form.value.html}</span>
  </div>

{* FOOTER *}
<div class="crm-submit-buttons">
{include file="CRM/common/formButtons.tpl" location="bottom"}
</div>
