<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.octopus8.iras
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:b5372e569df47eaea69437f1b370e6e9)
 */
use CRM_Irasdonation_ExtensionUtil as E;

/**
 * Database access object for the IrasResponseLog entity.
 */
class CRM_Irasdonation_DAO_IrasResponseLog extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_o8_iras_response_log';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * json response of request
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $response_body;

  /**
   * response code
   *
   * @var int|string
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $response_code;

  /**
   * Created date
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_o8_iras_response_log';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Iras Response Logs') : E::ts('Iras Response Log');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique ID'),
          'required' => TRUE,
          'where' => 'civicrm_o8_iras_response_log.id',
          'table_name' => 'civicrm_o8_iras_response_log',
          'entity' => 'IrasResponseLog',
          'bao' => 'CRM_Irasdonation_DAO_IrasResponseLog',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'response_body' => [
          'name' => 'response_body',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Response Body'),
          'description' => E::ts('json response of request'),
          'required' => TRUE,
          'where' => 'civicrm_o8_iras_response_log.response_body',
          'table_name' => 'civicrm_o8_iras_response_log',
          'entity' => 'IrasResponseLog',
          'bao' => 'CRM_Irasdonation_DAO_IrasResponseLog',
          'localizable' => 0,
          'html' => [
            'type' => 'ResponseBody',
          ],
          'add' => NULL,
        ],
        'response_code' => [
          'name' => 'response_code',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Response Code'),
          'description' => E::ts('response code'),
          'required' => FALSE,
          'where' => 'civicrm_o8_iras_response_log.response_code',
          'table_name' => 'civicrm_o8_iras_response_log',
          'entity' => 'IrasResponseLog',
          'bao' => 'CRM_Irasdonation_DAO_IrasResponseLog',
          'localizable' => 0,
          'html' => [
            'type' => 'ResponseCode',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Created Date'),
          'description' => E::ts('Created date'),
          'where' => 'civicrm_o8_iras_response_log.created_date',
          'table_name' => 'civicrm_o8_iras_response_log',
          'entity' => 'IrasResponseLog',
          'bao' => 'CRM_Irasdonation_DAO_IrasResponseLog',
          'localizable' => 0,
          'html' => [
            'type' => 'CreatedDate',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'o8_iras_response_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'o8_iras_response_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
