-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_o8_iras_response_log`;
DROP TABLE IF EXISTS `civicrm_o8_iras_donation`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_o8_iras_donation
-- *
-- * IRAS Donation Reporting tool
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_iras_donation` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `cdntaxreceipts_log_id` int COMMENT 'FK to Contact',
  `is_api` tinyint COMMENT 'api or offline report',
  `comment` text NULL COMMENT 'comment to sending item',
  `log_id` int unsigned NULL COMMENT 'FK to Contact Response log',
  `created_date` datetime COMMENT 'Created date',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_iras_donation_cdntaxreceipts_log_id FOREIGN KEY (`cdntaxreceipts_log_id`) REFERENCES `cdntaxreceipts_log`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_iras_response_log
-- *
-- * IRAS submissions response logs, keeps all submission values and responses
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_iras_response_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `validate_only` tinyint NULL DEFAULT true COMMENT 'validateOnly',
  `basis_year` varchar(4) NULL DEFAULT "" COMMENT 'BasisYear',
  `organisation_id_type` varchar(60) NULL DEFAULT "" COMMENT 'organisationIDType',
  `organisation_id_no` varchar(60) NULL DEFAULT "" COMMENT 'organisationIDNo',
  `organisation_name` varchar(60) NULL DEFAULT "" COMMENT 'organisationName',
  `batch_indicator` varchar(4) NULL DEFAULT "0" COMMENT 'batchIndicator',
  `authorised_person_id_no` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonIDNo',
  `authorised_person_name` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonName',
  `authorised_person_designation` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonDesignation',
  `telephone` varchar(60) NULL DEFAULT "" COMMENT 'telephone',
  `authorised_person_email` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonEmail',
  `num_of_records` int unsigned NULL DEFAULT 0 COMMENT 'numOfRecords',
  `total_donation_amount` int unsigned NULL DEFAULT 0 COMMENT 'totalDonationAmount',
  `response_body` text NOT NULL DEFAULT "" COMMENT 'json response of request',
  `response_code` int NULL DEFAULT NULL COMMENT 'response code',
  `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When the response was first received',
  PRIMARY KEY (`id`),
  INDEX `index_created_date`(created_date)
)
ENGINE=InnoDB;
