-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_o8_iras_donation_log`;
DROP TABLE IF EXISTS `civicrm_o8_iras_donation`;
DROP TABLE IF EXISTS `civicrm_o8_iras_response_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_o8_iras_response_log
-- *
-- * IRAS submissions response logs, keeps all submission values and responses
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_iras_response_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `is_api` tinyint NULL DEFAULT false COMMENT 'api or offline report',
  `validate_only` tinyint NULL DEFAULT true COMMENT 'validateOnly',
  `basis_year` varchar(4) NULL DEFAULT "" COMMENT 'BasisYear',
  `organisation_id_type` varchar(60) NULL DEFAULT "" COMMENT 'organisationIDType',
  `organisation_id_no` varchar(60) NULL DEFAULT "" COMMENT 'organisationIDNo',
  `organisation_name` varchar(60) NULL DEFAULT "" COMMENT 'organisationName',
  `batch_indicator` varchar(4) NULL DEFAULT "0" COMMENT 'batchIndicator',
  `authorised_person_id_no` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonIDNo',
  `authorised_person_name` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonName',
  `authorised_person_designation` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonDesignation',
  `telephone` varchar(60) NULL DEFAULT "" COMMENT 'telephone',
  `authorised_person_email` varchar(60) NULL DEFAULT "" COMMENT 'authorisedPersonEmail',
  `num_of_records` int unsigned NULL DEFAULT 0 COMMENT 'numOfRecords',
  `total_donation_amount` int unsigned NULL DEFAULT 0 COMMENT 'totalDonationAmount',
  `response_body` text NULL COMMENT 'json response of request',
  `response_code` int NULL DEFAULT NULL COMMENT 'response code',
  `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When the response was first received',
  PRIMARY KEY (`id`),
  INDEX `index_created_date`(created_date)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_iras_donation
-- *
-- * IRAS Donation Reporting tool
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_iras_donation` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `contribution_id` int unsigned NULL COMMENT 'FK to Contribution',
  `last_donation_log_id` int unsigned NULL COMMENT 'Last Iras Donation Log',
  `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When the response was first received',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_contribution_id`(contribution_id),
  UNIQUE INDEX `index_last_donation_log_id`(last_donation_log_id),
  INDEX `index_created_date`(created_date),
  CONSTRAINT FK_civicrm_o8_iras_donation_contribution_id FOREIGN KEY (`contribution_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_iras_donation_log
-- *
-- * IRAS Donation Log
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_iras_donation_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique IrasDonationLog ID',
  `record_id` int unsigned NULL DEFAULT 1 COMMENT 'recordID',
  `id_type` varchar(4) NULL DEFAULT "5" COMMENT 'idType',
  `id_number` varchar(12) NULL DEFAULT "" COMMENT 'idNumber',
  `individual_indicator` varchar(3) NULL DEFAULT "" COMMENT 'individualIndicator',
  `contact_name` varchar(80) NULL DEFAULT "" COMMENT 'name',
  `address_line1` varchar(160) NULL DEFAULT NULL COMMENT 'addressLine1',
  `address_line2` varchar(160) NULL DEFAULT NULL COMMENT 'addressLine2',
  `postal_code` varchar(60) NULL DEFAULT NULL COMMENT 'postalCode',
  `donation_amount` int unsigned NULL DEFAULT 0 COMMENT 'totalDonationAmount',
  `date_of_donation` varchar(8) NULL DEFAULT NULL COMMENT 'dateOfDonation',
  `receipt_num` varchar(10) NULL DEFAULT NULL COMMENT 'receiptNum',
  `type_of_donation` varchar(1) NULL DEFAULT "O" COMMENT 'typeOfDonation',
  `naming_donation` varchar(1) NULL DEFAULT "Z" COMMENT 'namingDonation',
  `iras_response_id` int unsigned COMMENT 'FK to IRAS Responses',
  `iras_donation_id` int unsigned COMMENT 'FK to IRAS Donations',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_iras_donation_log_iras_response_id FOREIGN KEY (`iras_response_id`) REFERENCES `civicrm_o8_iras_response_log`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_iras_donation_log_iras_donation_id FOREIGN KEY (`iras_donation_id`) REFERENCES `civicrm_o8_iras_donation`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
